# Generated by Django 4.1.2 on 2022-11-04 18:00

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=50, validators=[main_app.validators.validate_phone], verbose_name='Телефон'),
        ),
    ]
